# Generated by Django 5.2.6 on 2025-10-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
