# Generated by Django 5.2.6 on 2025-10-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizsession_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='option_char',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
