# Generated by Django 5.2.6 on 2025-11-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.AddField(
            model_name='quiz',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_covers/'),
        ),
    ]
